/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package screens;

import codes.Bebida;
import codes.Comanda;
import codes.Comida;
import codes.Couvert;
import codes.TipoBuffet;
import javax.swing.JOptionPane;

/**
 *
 * @author Eugênio
 */
public class TelaPrincipal extends javax.swing.JFrame {

    private Comanda comanda;
    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
    }//construtor ---------------
    
    public TipoBuffet identificarTipo () {
        if (jbllivre.isSelected()) {
            return TipoBuffet.LIVRE;
        } else if (jblquilo.isSelected()) {
            return TipoBuffet.QUILO;
        }
        return null;
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jblbebida1 = new javax.swing.JRadioButton();
        jblcouvert1 = new javax.swing.JRadioButton();
        jButton2 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jblnomeitem1 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jblvaloritem1 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jblcomida1 = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jblnomeitem = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jblvaloritem = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jblcomida = new javax.swing.JRadioButton();
        jblbebida = new javax.swing.JRadioButton();
        jblcouvert = new javax.swing.JRadioButton();
        jbllivre = new javax.swing.JRadioButton();
        jblquilo = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        jblpagar = new javax.swing.JButton();
        jblexibircomanda = new javax.swing.JButton();
        jblcriarcomanda = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();

        jLabel2.setText("jLabel2");

        buttonGroup1.add(jblbebida1);
        jblbebida1.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jblbebida1.setText("Bebida");
        jblbebida1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jblbebida1ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jblcouvert1);
        jblcouvert1.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jblcouvert1.setText("Couvert");
        jblcouvert1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jblcouvert1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jButton2.setText("Adicionar Item");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        jLabel8.setText("Nome Item");

        jLabel9.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        jLabel9.setText("Valor Item");

        jLabel10.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        jLabel10.setText("Tipo Item");

        buttonGroup1.add(jblcomida1);
        jblcomida1.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jblcomida1.setText("Comida");
        jblcomida1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jblcomida1ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Principal");
        setMinimumSize(new java.awt.Dimension(573, 525));

        jLabel1.setFont(new java.awt.Font("Segoe UI Light", 1, 24)); // NOI18N
        jLabel1.setText("Comanda");

        jLabel3.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        jLabel3.setText("Nome Item");

        jLabel4.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        jLabel4.setText("Valor Item");

        jLabel5.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        jLabel5.setText("Tipo Buffet");

        jLabel6.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        jLabel6.setText("Tipo Item");

        buttonGroup1.add(jblcomida);
        jblcomida.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jblcomida.setText("Comida");
        jblcomida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jblcomidaActionPerformed(evt);
            }
        });

        buttonGroup1.add(jblbebida);
        jblbebida.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jblbebida.setText("Bebida");
        jblbebida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jblbebidaActionPerformed(evt);
            }
        });

        buttonGroup1.add(jblcouvert);
        jblcouvert.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jblcouvert.setText("Couvert");
        jblcouvert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jblcouvertActionPerformed(evt);
            }
        });

        buttonGroup2.add(jbllivre);
        jbllivre.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jbllivre.setText("Livre");

        buttonGroup2.add(jblquilo);
        jblquilo.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jblquilo.setText("Quilo");

        jButton1.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jButton1.setText("Adicionar Item");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jblpagar.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jblpagar.setText("Pagar");
        jblpagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jblpagarActionPerformed(evt);
            }
        });

        jblexibircomanda.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jblexibircomanda.setText("Exibir Comanda");
        jblexibircomanda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jblexibircomandaActionPerformed(evt);
            }
        });

        jblcriarcomanda.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jblcriarcomanda.setText("Criar Comanda");
        jblcriarcomanda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jblcriarcomandaActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI Light", 1, 24)); // NOI18N
        jLabel7.setText("Produto");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(jbllivre)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jblquilo)
                        .addGap(69, 69, 69)
                        .addComponent(jblcriarcomanda))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jblnomeitem, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel6))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addComponent(jblcomida)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jblbebida))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jblvaloritem, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1)
                            .addComponent(jblcouvert))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 374, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 374, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(60, 60, 60))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jblpagar, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(jblexibircomanda)
                        .addGap(92, 92, 92))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jbllivre)
                    .addComponent(jblquilo)
                    .addComponent(jblcriarcomanda))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel7)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jblnomeitem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jblcomida)
                    .addComponent(jblbebida)
                    .addComponent(jblcouvert))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jblvaloritem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 89, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jblpagar)
                    .addComponent(jblexibircomanda))
                .addGap(57, 57, 57))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jblpagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jblpagarActionPerformed
            TelaPagamento telaPagamento = new TelaPagamento(comanda);
            telaPagamento.setVisible(true);       
            
    }//GEN-LAST:event_jblpagarActionPerformed

    private void jblexibircomandaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jblexibircomandaActionPerformed
        TelaExibirComanda telaExibirComanda = new TelaExibirComanda(comanda);
        telaExibirComanda.setVisible(true);
        
    }//GEN-LAST:event_jblexibircomandaActionPerformed

    private void jblcriarcomandaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jblcriarcomandaActionPerformed
        TipoBuffet tipo = identificarTipo();
        comanda = new Comanda(tipo);

        JOptionPane.showMessageDialog(this, "Comanda criada com sucesso!");
        
       
        
    }//GEN-LAST:event_jblcriarcomandaActionPerformed

    private void jblbebida1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jblbebida1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jblbebida1ActionPerformed

    private void jblcouvert1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jblcouvert1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jblcouvert1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jblcomida1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jblcomida1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jblcomida1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String nomeItem = jblnomeitem.getText();
        double valorItemCerto = Double.parseDouble(jblvaloritem.getText());

        if (jblcomida.isSelected()) {
            Comida comida = new Comida(nomeItem, valorItemCerto);
            comanda.incluirItem(comida, comanda);
        } else if (jblbebida.isSelected()) {
            Bebida bebida = new Bebida(nomeItem, valorItemCerto);
            comanda.incluirItem(bebida, comanda);
        } else if (jblcouvert.isSelected()) {
            Couvert couvert = new Couvert(nomeItem, valorItemCerto);
            comanda.incluirItem(couvert, comanda);
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jblcouvertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jblcouvertActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jblcouvertActionPerformed

    private void jblbebidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jblbebidaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jblbebidaActionPerformed

    private void jblcomidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jblcomidaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jblcomidaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JRadioButton jblbebida;
    private javax.swing.JRadioButton jblbebida1;
    private javax.swing.JRadioButton jblcomida;
    private javax.swing.JRadioButton jblcomida1;
    private javax.swing.JRadioButton jblcouvert;
    private javax.swing.JRadioButton jblcouvert1;
    private javax.swing.JButton jblcriarcomanda;
    private javax.swing.JButton jblexibircomanda;
    private javax.swing.JRadioButton jbllivre;
    private javax.swing.JTextField jblnomeitem;
    private javax.swing.JTextField jblnomeitem1;
    private javax.swing.JButton jblpagar;
    private javax.swing.JRadioButton jblquilo;
    private javax.swing.JTextField jblvaloritem;
    private javax.swing.JTextField jblvaloritem1;
    // End of variables declaration//GEN-END:variables
}
