/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package screens;
import codes.Aluno;
import codes.Professor;
import codes.Titulacao;
import codes.Turma;
import codes.Turno;
import java.util.ArrayList;
import javax.swing.JOptionPane;


/**
 *
 * @author Eugênio
 */
public class ScreenEscola extends javax.swing.JFrame {
    
    private Professor professor;
    private Turma turma;
    public ArrayList<Turma> turmas = new ArrayList<>();

    /**
     * Creates new form ScreenEscola
     */

    public ScreenEscola() {
        initComponents();
        
    }//construtor
    

    public Turno identificarTurno () {
        if (jblmatutino.isSelected()) {
            return Turno.MATUTINO;
            
        } else if (jblvespertino.isSelected()) {
            return Turno.VESPERTINO;
            
        } else if (jblnoturno.isSelected()) {
            return Turno.NOTURNO;
            
        }
        return null;
    }
    
    
    public Titulacao identificarTitulacao () {
        if (jblgraduacao.isSelected()) {
            return Titulacao.GRADUACAO;
            
        } else if (jblmestrado.isSelected()) {
            return Titulacao.MESTRADO;
            
        } else if (jbldoutorado.isSelected()) {
            return Titulacao.DOUTORADO;
            
        }
        return null;
    }
    
    
    public void incluirAluno (Aluno aluno, String disciplina, ArrayList<Turma> turmas) {
        boolean turmaEncontrada = false;
        
        for (Turma a : turmas) {
            if (a.getDisciplina().equalsIgnoreCase(disciplina)) {
                a.getAlunos().add(aluno); //não sei se vai dar certo
                turmaEncontrada = true;
                break;
            }
        }
        
        if (turmaEncontrada != false) {
            JOptionPane.showMessageDialog(null, "Aluno foi incluído em " + disciplina + "!");
        } else if (turmaEncontrada != true) {
            JOptionPane.showMessageDialog(null, "Turma não foi encontrada");
        }
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */


    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jbldisciplina = new javax.swing.JTextField();
        jblmatutino = new javax.swing.JRadioButton();
        jblvespertino = new javax.swing.JRadioButton();
        jblnoturno = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jblemail = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jblnomeprof = new javax.swing.JTextField();
        jblgraduacao = new javax.swing.JRadioButton();
        jblmestrado = new javax.swing.JRadioButton();
        jbldoutorado = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jblincluiraluno = new javax.swing.JButton();
        jbllistardadosturma = new javax.swing.JButton();
        jblcriarturma = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI Light", 1, 24)); // NOI18N
        jLabel1.setText("Turma");

        jLabel2.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        jLabel2.setText("Disciplina");

        buttonGroup1.add(jblmatutino);
        jblmatutino.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jblmatutino.setText("Matutino");

        buttonGroup1.add(jblvespertino);
        jblvespertino.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jblvespertino.setText("Vespertino");

        buttonGroup1.add(jblnoturno);
        jblnoturno.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jblnoturno.setText("Noturno");

        jLabel3.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        jLabel3.setText("Turno");

        jLabel4.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        jLabel4.setText("Email");

        jLabel5.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        jLabel5.setText("Titulação");

        jLabel6.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        jLabel6.setText("Nome");

        buttonGroup2.add(jblgraduacao);
        jblgraduacao.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jblgraduacao.setText("Graduação");
        jblgraduacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jblgraduacaoActionPerformed(evt);
            }
        });

        buttonGroup2.add(jblmestrado);
        jblmestrado.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jblmestrado.setText("Mestrado");

        buttonGroup2.add(jbldoutorado);
        jbldoutorado.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jbldoutorado.setText("Doutorado");
        jbldoutorado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbldoutoradoActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI Light", 1, 24)); // NOI18N
        jLabel7.setText("Professor");

        jblincluiraluno.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jblincluiraluno.setText("Incluir Aluno");
        jblincluiraluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jblincluiralunoActionPerformed(evt);
            }
        });

        jbllistardadosturma.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jbllistardadosturma.setText("Listar dados turma");
        jbllistardadosturma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbllistardadosturmaActionPerformed(evt);
            }
        });

        jblcriarturma.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jblcriarturma.setText("CriarTurma");
        jblcriarturma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jblcriarturmaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jblmatutino)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jblvespertino)
                                        .addGap(18, 18, 18)
                                        .addComponent(jblnoturno))
                                    .addComponent(jbldisciplina)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(18, 18, 18)
                                .addComponent(jblnomeprof))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18)
                                .addComponent(jblgraduacao)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jblmestrado)
                                .addGap(18, 18, 18)
                                .addComponent(jbldoutorado, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(jblemail))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jblincluiraluno)
                                .addGap(18, 18, 18)
                                .addComponent(jblcriarturma)
                                .addGap(18, 18, 18)
                                .addComponent(jbllistardadosturma))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel7)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jSeparator2))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel1)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 446, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jbldisciplina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jblmatutino)
                    .addComponent(jblvespertino)
                    .addComponent(jblnoturno)
                    .addComponent(jLabel3))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jblnomeprof, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jblemail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jblgraduacao)
                    .addComponent(jblmestrado)
                    .addComponent(jbldoutorado))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 86, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jblincluiraluno)
                    .addComponent(jblcriarturma)
                    .addComponent(jbllistardadosturma))
                .addGap(45, 45, 45))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbldoutoradoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbldoutoradoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbldoutoradoActionPerformed

    private void jblgraduacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jblgraduacaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jblgraduacaoActionPerformed

    private void jblcriarturmaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jblcriarturmaActionPerformed
                    String disciplina = jbldisciplina.getText();                   
                    Turno turno = identificarTurno();
                    String nomeProf = jblnomeprof.getText();
                    String email = jblemail.getText();                            
                    Titulacao titulacao = identificarTitulacao();
                    
                    try {
                        professor = new Professor(nomeProf, email, titulacao);
                        turma = new Turma(disciplina, turno, professor);
                        turmas.add(turma);
                        JOptionPane.showMessageDialog(this, "Turma criada!");
                                              
                    } catch (IllegalArgumentException e) {
                        JOptionPane.showMessageDialog(null, e.getMessage());
                    }
               
    }//GEN-LAST:event_jblcriarturmaActionPerformed

    private void jblincluiralunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jblincluiralunoActionPerformed
                ScreenAluno screenAluno = new ScreenAluno(this);
                screenAluno.setVisible(true);
                
    }//GEN-LAST:event_jblincluiralunoActionPerformed

    private void jbllistardadosturmaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbllistardadosturmaActionPerformed
           ScreenExibir screenExibir = new ScreenExibir(this);
           screenExibir.setVisible(true);
           
    }//GEN-LAST:event_jbllistardadosturmaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ScreenEscola.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ScreenEscola.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ScreenEscola.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ScreenEscola.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ScreenEscola().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JButton jblcriarturma;
    private javax.swing.JTextField jbldisciplina;
    private javax.swing.JRadioButton jbldoutorado;
    private javax.swing.JTextField jblemail;
    private javax.swing.JRadioButton jblgraduacao;
    private javax.swing.JButton jblincluiraluno;
    private javax.swing.JButton jbllistardadosturma;
    private javax.swing.JRadioButton jblmatutino;
    private javax.swing.JRadioButton jblmestrado;
    private javax.swing.JTextField jblnomeprof;
    private javax.swing.JRadioButton jblnoturno;
    private javax.swing.JRadioButton jblvespertino;
    // End of variables declaration//GEN-END:variables
}
