/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Tela;

import com.mycompany.lista6.FaixaIrpf;
import com.mycompany.lista6.Funcionario;
import java.text.DecimalFormat;



/**
 *
 * @author Eugênio
 */
public class InterfaceAtividadeLista6 extends javax.swing.JFrame {

    /**
     * Creates new form InterfaceAtividadeLista6
     */
    public InterfaceAtividadeLista6() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jblavaliar = new javax.swing.JButton();
        jblsalario = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jblpainel = new javax.swing.JTextPane();
        jblnome = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Salário:");

        jblavaliar.setText("Avaliar");
        jblavaliar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jblavaliarActionPerformed(evt);
            }
        });

        jblsalario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jblsalarioActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(jblpainel);

        jblnome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jblnomeActionPerformed(evt);
            }
        });

        jLabel2.setText("Nome:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 327, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jblavaliar)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jblnome, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jblsalario, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jblavaliar, jblsalario});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jblsalario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jblnome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jblavaliar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jblsalarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jblsalarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jblsalarioActionPerformed

    private void jblavaliarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jblavaliarActionPerformed
        jblpainel.setText("");
        
        
        double salario = Double.parseDouble(jblsalario.getText());
        
        
        Funcionario f = new Funcionario(jblnome.getText(), Double.parseDouble(jblsalario.getText()));
        FaixaIrpf quadrante = f.identificarFaixaIrpf();
        
        DecimalFormat df = new DecimalFormat("0.00");
        
        switch (quadrante) {
                case PRIMEIRA:
                jblpainel.setText("Você pertence a Primeira Faixa"
                        + " - Imposto: " + "R$ " + df.format(f.calcularIrpf()));

                break;
                case SEGUNDA:
                jblpainel.setText("Você pertence a Seunda Faixa"
                        + " - Imposto: " + "R$ " + df.format(f.calcularIrpf()));
                break;
                
                case TERCEIRA:
                
                jblpainel.setText("Você pertence a Terceira Faixa"
                        + " - Imposto: " + "R$ " + df.format(f.calcularIrpf()));
                break;
   
                case QUARTA:
                
                jblpainel.setText("Você pertence a Quarta Faixa"
                        + " - Imposto: " + "R$ " + df.format(f.calcularIrpf()));
                break;
                
                case QUINTA:
                
                jblpainel.setText("Você pertence a Quinta Faixa"
                        + " - Imposto: " + "R$ " + df.format(f.calcularIrpf()));
                break;
                default:
                throw new AssertionError();
        }
        
        
    }//GEN-LAST:event_jblavaliarActionPerformed

    private void jblnomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jblnomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jblnomeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfaceAtividadeLista6.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfaceAtividadeLista6.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfaceAtividadeLista6.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfaceAtividadeLista6.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfaceAtividadeLista6().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jblavaliar;
    private javax.swing.JTextField jblnome;
    private javax.swing.JTextPane jblpainel;
    private javax.swing.JTextField jblsalario;
    // End of variables declaration//GEN-END:variables
}
