//Eugênio Victor Erbs | Manhã BCC
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Tela;

import Codes.Estadia;
import javax.swing.JOptionPane;


/**
 *
 * @author Eugênio
 */
public class TelaEstadia extends javax.swing.JFrame {

    /**
     * Creates new form TelaEstadia
     */
    public TelaEstadia() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jblmes = new javax.swing.JFormattedTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jblpainel = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        jblquantidadedias = new javax.swing.JFormattedTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jblavaliar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(null);
        setMinimumSize(new java.awt.Dimension(474, 619));
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 18)); // NOI18N
        jLabel2.setText("Mês");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(120, 180, 130, 20);

        jblmes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jblmesActionPerformed(evt);
            }
        });
        getContentPane().add(jblmes);
        jblmes.setBounds(120, 220, 210, 30);

        jblpainel.setColumns(20);
        jblpainel.setRows(5);
        jScrollPane1.setViewportView(jblpainel);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(40, 450, 390, 120);

        jLabel3.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 18)); // NOI18N
        jLabel3.setText("ficará hospedado!");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(160, 100, 160, 25);

        jblquantidadedias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jblquantidadediasActionPerformed(evt);
            }
        });
        getContentPane().add(jblquantidadedias);
        jblquantidadedias.setBounds(120, 310, 210, 30);

        jLabel4.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 18)); // NOI18N
        jLabel4.setText("Quantidade de dias");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(120, 270, 220, 20);

        jLabel5.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 18)); // NOI18N
        jLabel5.setText("Nos campos a baixo informe");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(120, 40, 250, 25);

        jLabel6.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 18)); // NOI18N
        jLabel6.setText("o período em que você");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(140, 70, 200, 25);

        jblavaliar.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 18)); // NOI18N
        jblavaliar.setText("Avaliar");
        jblavaliar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jblavaliarActionPerformed(evt);
            }
        });
        getContentPane().add(jblavaliar);
        jblavaliar.setBounds(120, 380, 210, 32);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jblmesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jblmesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jblmesActionPerformed

    private void jblquantidadediasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jblquantidadediasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jblquantidadediasActionPerformed

    private void jblavaliarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jblavaliarActionPerformed
        /**
         * Tranforma o dia, dado como texto, em int para usar de parâmetro.
         * Cria o objeto com os parametros passados na tela, e entrega o preço resultado cálculo para o cliente
         * na tela painel.
         */
        try {        
        String mes = jblmes.getText();
        int dias = Integer.parseInt(jblquantidadedias.getText());
        
        Estadia client = new Estadia(mes, dias);
        
        
        jblpainel.setText("Valor da estadia: " + client.precoPagar());
            
        } catch (IllegalArgumentException e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
        

        
        
    }//GEN-LAST:event_jblavaliarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaEstadia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaEstadia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaEstadia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaEstadia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaEstadia().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jblavaliar;
    private javax.swing.JFormattedTextField jblmes;
    private javax.swing.JTextArea jblpainel;
    private javax.swing.JFormattedTextField jblquantidadedias;
    // End of variables declaration//GEN-END:variables
}
