
import model.Ponto;
import model.Quadrante;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Eugênio
 */
public class TelaPontos extends javax.swing.JFrame {

    /**
     * Creates new form TelaPontos
     */
    public TelaPontos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jblEixoX = new javax.swing.JTextField();
        jblEixoY = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jblIncideSobreOEixoY = new javax.swing.JCheckBox();
        jblNo1Quadrante = new javax.swing.JCheckBox();
        jblNo2Quadrante = new javax.swing.JCheckBox();
        jblNo4Quadrante = new javax.swing.JCheckBox();
        jblNo3Quadrante = new javax.swing.JCheckBox();
        jblIncideSobreOEixoX = new javax.swing.JCheckBox();
        jblAvaliar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Eixo X:");

        jLabel2.setText("Eixo Y:");

        jblEixoX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jblEixoXActionPerformed(evt);
            }
        });

        jblEixoY.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jblEixoYActionPerformed(evt);
            }
        });

        jLabel5.setText("Posição:");

        jblIncideSobreOEixoY.setText("Incide sobre o Eixo Y");

        jblNo1Quadrante.setText("No 1 Quadrante");

        jblNo2Quadrante.setText("No 2 Quadrante");

        jblNo4Quadrante.setText("No 4 Quadrante");

        jblNo3Quadrante.setText("No 3 Quadrante");

        jblIncideSobreOEixoX.setText("Incide sobre o Eixo X");

        jblAvaliar.setText("Avaliar");
        jblAvaliar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jblAvaliarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jblIncideSobreOEixoX)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jblNo1Quadrante)
                            .addComponent(jblNo2Quadrante)
                            .addComponent(jblNo3Quadrante)
                            .addComponent(jblNo4Quadrante)
                            .addComponent(jblIncideSobreOEixoY)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(jblEixoY, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(jblEixoX)))
                        .addGap(18, 18, 18)
                        .addComponent(jblAvaliar))
                    .addComponent(jLabel5))
                .addContainerGap(27, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(211, 211, 211)
                    .addComponent(jLabel3)
                    .addContainerGap(142, Short.MAX_VALUE)))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(211, 211, 211)
                    .addComponent(jLabel4)
                    .addContainerGap(142, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jblEixoX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(jblAvaliar)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jblEixoY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jblIncideSobreOEixoX)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jblIncideSobreOEixoY)
                .addGap(5, 5, 5)
                .addComponent(jblNo1Quadrante)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jblNo2Quadrante)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jblNo3Quadrante)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jblNo4Quadrante)
                .addGap(47, 47, 47))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(125, 125, 125)
                    .addComponent(jLabel3)
                    .addContainerGap(244, Short.MAX_VALUE)))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(125, 125, 125)
                    .addComponent(jLabel4)
                    .addContainerGap(244, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jblEixoXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jblEixoXActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jblEixoXActionPerformed

    private void jblEixoYActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jblEixoYActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jblEixoYActionPerformed

    private void jblAvaliarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jblAvaliarActionPerformed
            jblNo1Quadrante.setSelected(false);
            jblNo2Quadrante.setSelected(false);
            jblNo3Quadrante.setSelected(false);
            jblNo4Quadrante.setSelected(false);
            jblIncideSobreOEixoX.setSelected(false);
            jblIncideSobreOEixoY.setSelected(false);
        
        int EixoX = Integer.parseInt(jblEixoX.getText());
        int EixoY = Integer.parseInt(jblEixoY.getText());
        
        Ponto p = new Ponto(Integer.parseInt(jblEixoX.getText()), Integer.parseInt(jblEixoY.getText()));
            
        Quadrante quadrante = p.identificarQuadrante();
        
        switch (quadrante) {
            case PRIMEIRO:
                jblNo1Quadrante.setSelected(true);
            break;
            case SEGUNDO:
                 jblNo2Quadrante.setSelected(true);
            break;
            case TERCEIRO:
                 jblNo3Quadrante.setSelected(true);
            break;
            case QUARTO:
                jblNo4Quadrante.setSelected(true);
            break;
            default:
                throw new AssertionError();
        }
        
        if (EixoX == 0){
            jblIncideSobreOEixoX.setSelected(true);
        } else if (EixoY == 0){
            jblIncideSobreOEixoY.setSelected(true);
        }
        
        
    }//GEN-LAST:event_jblAvaliarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPontos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPontos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPontos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPontos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPontos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jblAvaliar;
    private javax.swing.JTextField jblEixoX;
    private javax.swing.JTextField jblEixoY;
    private javax.swing.JCheckBox jblIncideSobreOEixoX;
    private javax.swing.JCheckBox jblIncideSobreOEixoY;
    private javax.swing.JCheckBox jblNo1Quadrante;
    private javax.swing.JCheckBox jblNo2Quadrante;
    private javax.swing.JCheckBox jblNo3Quadrante;
    private javax.swing.JCheckBox jblNo4Quadrante;
    // End of variables declaration//GEN-END:variables
}
