/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package screens;

import codes.Empresa;
import codes.Funcionario1;
import codes.Programador;
import codes.Venda;
import codes.Vendedor;
import javax.swing.JOptionPane;


/**
 *
 * @author Eugênio
 */
public class TelaRegistrar extends javax.swing.JFrame {

    private Empresa empresa;
    protected Programador programador;
    protected Funcionario1 outro;
    
    /**
     * Creates new form TelaFuncionario
     */
    public TelaRegistrar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel7 = new javax.swing.JLabel();
        jblprogramadorbg = new javax.swing.JRadioButton();
        jblnomefuncionario = new javax.swing.JFormattedTextField();
        jblvendedorbg = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jblsalariobase = new javax.swing.JFormattedTextField();
        jLabel5 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jblconfirmar = new javax.swing.JButton();
        jblcancelar = new javax.swing.JButton();
        jSeparator4 = new javax.swing.JSeparator();
        jblnomeempresa = new javax.swing.JFormattedTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jbloutrobg = new javax.swing.JRadioButton();
        jblexibir = new javax.swing.JButton();
        jblcalculargastos = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(657, 529));
        setMinimumSize(new java.awt.Dimension(657, 529));

        jLabel7.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        jLabel7.setText("Função:");

        buttonGroup1.add(jblprogramadorbg);
        jblprogramadorbg.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        jblprogramadorbg.setText("Programador");
        jblprogramadorbg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jblprogramadorbgActionPerformed(evt);
            }
        });

        buttonGroup1.add(jblvendedorbg);
        jblvendedorbg.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        jblvendedorbg.setText("Vendedor");

        jLabel4.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        jLabel4.setText("Nome:");

        jLabel2.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        jLabel2.setText("Funcionário");

        jLabel5.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        jLabel5.setText("Salário Base:");

        jblconfirmar.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jblconfirmar.setText("Confirmar");
        jblconfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jblconfirmarActionPerformed(evt);
            }
        });

        jblcancelar.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jblcancelar.setText("Voltar");
        jblcancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jblcancelarActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        jLabel3.setText("Nome:");

        jLabel1.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        jLabel1.setText("Empresa");

        buttonGroup1.add(jbloutrobg);
        jbloutrobg.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        jbloutrobg.setSelected(true);
        jbloutrobg.setText("Outro");
        jbloutrobg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbloutrobgActionPerformed(evt);
            }
        });

        jblexibir.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jblexibir.setText("Exibir Funcionários");
        jblexibir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jblexibirActionPerformed(evt);
            }
        });

        jblcalculargastos.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jblcalculargastos.setText("Calcular Gastos Salariais");
        jblcalculargastos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jblcalculargastosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 482, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jblnomefuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jblsalariobase, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(123, 123, 123)
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addComponent(jblprogramadorbg, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jblvendedorbg, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbloutrobg, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSeparator2))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jblconfirmar)
                        .addGap(18, 18, 18)
                        .addComponent(jblcancelar)
                        .addGap(105, 105, 105))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator3)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jblnomeempresa, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jblcalculargastos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jblexibir, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(19, 19, 19)))))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jblnomeempresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jblexibir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jblcalculargastos)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(61, 61, 61)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jblnomefuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jblsalariobase, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jblprogramadorbg)
                    .addComponent(jblvendedorbg)
                    .addComponent(jbloutrobg))
                .addGap(31, 31, 31)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jblconfirmar)
                    .addComponent(jblcancelar))
                .addGap(33, 33, 33))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jblprogramadorbgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jblprogramadorbgActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jblprogramadorbgActionPerformed

    private void jblcancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jblcancelarActionPerformed

        dispose();
    }//GEN-LAST:event_jblcancelarActionPerformed

    private void jblconfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jblconfirmarActionPerformed
        try {
            empresa = new Empresa(jblnomeempresa.getText());
        
        if (jblprogramadorbg.isSelected()) {
            programador = new Programador(jblnomefuncionario.getText(), Double.parseDouble(jblsalariobase.getText()));
            empresa.incluirFuncionario(programador);
            TelaProgramador telaProgramador = new TelaProgramador(programador);
            telaProgramador.setVisible(true);
            
        } else if (jblvendedorbg.isSelected()) {
            String nomeVendedor = jblnomefuncionario.getText();
            double salarioBase = Double.parseDouble(jblsalariobase.getText());
            TelaVendedor telaVendedor = new TelaVendedor(nomeVendedor, salarioBase, empresa);
            telaVendedor.setVisible(true);
        } else {
            outro = new Funcionario1(jblnomefuncionario.getText(), Double.parseDouble(jblsalariobase.getText()));
            empresa.incluirFuncionario(outro);
            JOptionPane.showMessageDialog(this, "Funcionário registrado com sucesso!");
            
        }
            
        } catch (IllegalArgumentException e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
               
    }//GEN-LAST:event_jblconfirmarActionPerformed

    private void jbloutrobgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbloutrobgActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbloutrobgActionPerformed

    private void jblexibirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jblexibirActionPerformed
        StringBuilder dados = new StringBuilder();
        
        for (Funcionario1 a : empresa.getFuncionarios()) {
            dados.append("Nome: ").append(a.getNome()).append(" - Salario base: R$ ").append(a.getSalarioBase()).append("\n");
            
            if (a instanceof Programador) {
                Programador p = (Programador) a;
                for (String s : p.getLinguagens()) {
                    dados.append(s).append(" - ");
                }
                dados.append("\n");
            } else if (a instanceof Vendedor) {
                Vendedor v = (Vendedor) a;
                dados.append("Comissão: ").append(v.getPercentualComissao()).append("\n");
                for(Venda venda : v.getVendas()) {
                    dados.append(venda.getValor()).append(" - ");
                }
                dados.append("\n");
            }
            dados.append("Salario: ").append(a.calcularSalario()).append("\n");
            
        }
        JOptionPane.showMessageDialog(this, dados.toString());
        
    }//GEN-LAST:event_jblexibirActionPerformed

    private void jblcalculargastosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jblcalculargastosActionPerformed
        JOptionPane.showMessageDialog(this, "Gasto total salarial da empresa: R$ " + empresa.cacularCustosSalarios());
    }//GEN-LAST:event_jblcalculargastosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaRegistrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaRegistrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaRegistrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaRegistrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaRegistrar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JButton jblcalculargastos;
    private javax.swing.JButton jblcancelar;
    private javax.swing.JButton jblconfirmar;
    private javax.swing.JButton jblexibir;
    private javax.swing.JFormattedTextField jblnomeempresa;
    private javax.swing.JFormattedTextField jblnomefuncionario;
    private javax.swing.JRadioButton jbloutrobg;
    private javax.swing.JRadioButton jblprogramadorbg;
    private javax.swing.JFormattedTextField jblsalariobase;
    private javax.swing.JRadioButton jblvendedorbg;
    // End of variables declaration//GEN-END:variables
}
