/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package screens;

import codes.ContaLuz;
import java.time.LocalDate;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author Eugênio
 */
public class ScreenContaLuz extends javax.swing.JFrame {

    ArrayList<ContaLuz> contas = new ArrayList<>();
    private ContaLuz contaLuz;
    
    /**
     * Creates new form ScreenContaLuz
     */
    public ScreenContaLuz() {
        initComponents();
    }//construtor
    
    
     public String exibirTodasContas (ArrayList<ContaLuz> contas) {
        StringBuilder dados = new StringBuilder();
        
        for (ContaLuz a : contas) {
            dados.append("Data leitura: ").append(a.getDataLeituraRelogio()).append("\n")
            .append("Número da leitura: ").append(a.getNumeroLeitura()).append("\n")
            .append("Kw gasto: ").append(a.getQuantidadeKwGastaMes()).append("\n")
            .append("Valor a pagar: ").append(a.getValorConta()).append("\n")
            .append("Data pagamento: ").append(a.getDataPagamento()).append("\n")
            .append("Média consumo: ").append(a.getMediaConsumo()).append("\n")
            .append("---------------------------------------------------------------------\n");
        }
        
        return dados.toString();
    }     
    
    
    public String contaMenorConsumo (ArrayList<ContaLuz> contas) {
        StringBuilder dadosDoMes = new StringBuilder();
        
        int valorKwMenor = Integer.MAX_VALUE;
        
        for (ContaLuz a : contas) {
            if (a.getQuantidadeKwGastaMes() < valorKwMenor) {
                valorKwMenor = a.getQuantidadeKwGastaMes();
            }           
        }
        
        ContaLuz contaMenor = null;
        
        for (ContaLuz b : contas) {
            if (b.getQuantidadeKwGastaMes() == valorKwMenor) {
                contaMenor = b;
            }
        }
        
        dadosDoMes.append("Menor consumo - KW: ").append(contaMenor.getQuantidadeKwGastaMes()).append("Data: ").append(contaMenor.getDataLeituraRelogio());
        
        return dadosDoMes.toString();
    }
    
    
    public String contaMaiorConsumo (ArrayList<ContaLuz> contas) {
        StringBuilder dadosDoMes = new StringBuilder();
        
        int valorKwMaior = Integer.MIN_VALUE;
        
        for (ContaLuz a : contas) {
            if (a.getQuantidadeKwGastaMes() > valorKwMaior) {
                valorKwMaior = a.getQuantidadeKwGastaMes();
            }           
        }
        
        ContaLuz contaMaior = null;
        
        for (ContaLuz b : contas) {
            if (b.getQuantidadeKwGastaMes() == valorKwMaior) {
                contaMaior = b;
            }
        }
        
        dadosDoMes.append("Maior consumo  -  KW: ").append(contaMaior.getQuantidadeKwGastaMes()).append("  -  ").append("Data: ").append(contaMaior.getDataLeituraRelogio());
        
        return dadosDoMes.toString();
    }
    
    
    public double calcularMediaConsumo (int qntKwMes) {
        double calculo = qntKwMes / 30;
        
        return calculo;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jblnumeroleitura1 = new javax.swing.JTextField();
        jblkwgasta1 = new javax.swing.JTextField();
        jblvalorapagar1 = new javax.swing.JTextField();
        jbldataleitura1 = new javax.swing.JButton();
        jblcalcularmedia1 = new javax.swing.JButton();
        jbldatapagamento1 = new javax.swing.JButton();
        jbllimpar1 = new javax.swing.JButton();
        jblconfirmar1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jblnumeroleitura = new javax.swing.JTextField();
        jblkwgasta = new javax.swing.JTextField();
        jblvalorapagar = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        jblpainel = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        jblcadastrarconta = new javax.swing.JButton();
        jblmesmaiorgasto = new javax.swing.JButton();
        jblmesmenorgasto = new javax.swing.JButton();
        jblexibircontas = new javax.swing.JButton();

        jLabel7.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel7.setText("DATA LEITURA");

        jLabel8.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel8.setText("NÚMERO LEITURA");

        jLabel9.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel9.setText("QUANTIDADE DE KW GASTA NO MÊS");

        jLabel10.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel10.setText("VALOR A PAGAR");

        jLabel11.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel11.setText("DATA PAGAMENTO");

        jLabel12.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel12.setText("MEDIA CONSUMO");

        jbldataleitura1.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jbldataleitura1.setText("Registrar");

        jblcalcularmedia1.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jblcalcularmedia1.setText("Calcular");

        jbldatapagamento1.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jbldatapagamento1.setText("Registrar");

        jbllimpar1.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jbllimpar1.setText("Limpar");
        jbllimpar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbllimpar1ActionPerformed(evt);
            }
        });

        jblconfirmar1.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jblconfirmar1.setText("Confirmar");
        jblconfirmar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jblconfirmar1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jblcalcularmedia1))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jbldatapagamento1))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jblvalorapagar1, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jblkwgasta1, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jblnumeroleitura1, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jbldataleitura1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jblconfirmar1)
                .addGap(18, 18, 18)
                .addComponent(jbllimpar1)
                .addGap(28, 28, 28))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jbldataleitura1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jblnumeroleitura1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jblkwgasta1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jblvalorapagar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jbldatapagamento1))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jblcalcularmedia1))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbllimpar1)
                    .addComponent(jblconfirmar1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tela Principal");
        setMinimumSize(new java.awt.Dimension(521, 453));

        jLabel2.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel2.setText("NÚMERO LEITURA");

        jLabel3.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel3.setText("QUANTIDADE DE KW GASTA NO MÊS");

        jLabel4.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel4.setText("VALOR A PAGAR");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 501, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jblkwgasta, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jblvalorapagar, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jblnumeroleitura, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jblvalorapagar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jblnumeroleitura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jblkwgasta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(71, 71, 71)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jblpainel.setColumns(20);
        jblpainel.setRows(5);
        jScrollPane1.setViewportView(jblpainel);

        jblcadastrarconta.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jblcadastrarconta.setText("Cadastrar conta");
        jblcadastrarconta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jblcadastrarcontaActionPerformed(evt);
            }
        });

        jblmesmaiorgasto.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jblmesmaiorgasto.setText("Exibir mês maior gasto");
        jblmesmaiorgasto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jblmesmaiorgastoActionPerformed(evt);
            }
        });

        jblmesmenorgasto.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jblmesmenorgasto.setText("Exibir mês menor gasto");
        jblmesmenorgasto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jblmesmenorgastoActionPerformed(evt);
            }
        });

        jblexibircontas.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jblexibircontas.setText("Exibir contas");
        jblexibircontas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jblexibircontasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jblcadastrarconta)
                .addGap(18, 18, 18)
                .addComponent(jblmesmenorgasto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jblmesmaiorgasto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jblexibircontas)
                .addContainerGap(25, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jblcadastrarconta)
                    .addComponent(jblmesmaiorgasto)
                    .addComponent(jblmesmenorgasto)
                    .addComponent(jblexibircontas))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 580, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jblmesmaiorgastoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jblmesmaiorgastoActionPerformed
            String contaMaiorConsumo = contaLuz.contaMaiorConsumo(contas);
            jblpainel.setText(contaMaiorConsumo);
            
    }//GEN-LAST:event_jblmesmaiorgastoActionPerformed

    private void jbllimpar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbllimpar1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbllimpar1ActionPerformed

    private void jblconfirmar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jblconfirmar1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jblconfirmar1ActionPerformed

    private void jblcadastrarcontaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jblcadastrarcontaActionPerformed
            LocalDate dataLeitura = LocalDate.now();
            String numeroLeitura = jblnumeroleitura.getText();
            String qntKwMesString = jblkwgasta.getText();
            int qntKwMes = Integer.parseInt(qntKwMesString);
            String valorContaString = jblvalorapagar.getText();
            double valorConta = Double.parseDouble(valorContaString);
            LocalDate dataPagamento = LocalDate.now();
            double mediaConsumo = calcularMediaConsumo(qntKwMes);
        
            try {
                contaLuz = new ContaLuz(dataLeitura, numeroLeitura, qntKwMes, valorConta, dataPagamento, mediaConsumo);
                contas.add(contaLuz);
                JOptionPane.showMessageDialog(null, "Conta cadastrada com sucesso :)");

                } catch (IllegalArgumentException e) {
                   JOptionPane.showMessageDialog(null, e.getMessage());
                   
              }
             
    }//GEN-LAST:event_jblcadastrarcontaActionPerformed

    private void jblmesmenorgastoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jblmesmenorgastoActionPerformed
            String contaMenorConsumo = contaLuz.contaMenorConsumo(contas);
            jblpainel.setText(contaMenorConsumo);
            
    }//GEN-LAST:event_jblmesmenorgastoActionPerformed

    private void jblexibircontasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jblexibircontasActionPerformed
        String exibir = exibirTodasContas(contas);
        jblpainel.setText(exibir);
        
    }//GEN-LAST:event_jblexibircontasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ScreenContaLuz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ScreenContaLuz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ScreenContaLuz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ScreenContaLuz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ScreenContaLuz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton jblcadastrarconta;
    private javax.swing.JButton jblcalcularmedia1;
    private javax.swing.JButton jblconfirmar1;
    private javax.swing.JButton jbldataleitura1;
    private javax.swing.JButton jbldatapagamento1;
    private javax.swing.JButton jblexibircontas;
    private javax.swing.JTextField jblkwgasta;
    private javax.swing.JTextField jblkwgasta1;
    private javax.swing.JButton jbllimpar1;
    private javax.swing.JButton jblmesmaiorgasto;
    private javax.swing.JButton jblmesmenorgasto;
    private javax.swing.JTextField jblnumeroleitura;
    private javax.swing.JTextField jblnumeroleitura1;
    private javax.swing.JTextArea jblpainel;
    private javax.swing.JTextField jblvalorapagar;
    private javax.swing.JTextField jblvalorapagar1;
    // End of variables declaration//GEN-END:variables
}
